### ISSUE TITLE
An error has occurred

### ISSUE THREAD

**Issue by askarkurymbayev** [ioprev/shelly-firmware#7]
When trying to compile it gives the following error

INFO:	Shelly firmware binary download tool. Version 0.1
INFO:	Downloading firmware binary file for device SHSW-1
INFO:	Output file is set to: firmware.bin
INFO:	Found platform switch1 in firmware package
Traceback (most recent call last):
  File "/home/ak/shelly-firmware/./shelly_firmware.py", line 306, in <module>
    main()
  File "/home/ak/shelly-firmware/./shelly_firmware.py", line 297, in main
    download_and_build_firmware(firmware_url, args.output)
  File "/home/ak/shelly-firmware/./shelly_firmware.py", line 116, in download_and_build_firmware
    build_firmware(fw_pkg.content, output_file)
  File "/home/ak/shelly-firmware/./shelly_firmware.py", line 91, in build_firmware
    part_data = fs_inject_hwinfo(part_data, platform_name)
  File "/home/ak/shelly-firmware/./shelly_firmware.py", line 141, in fs_inject_hwinfo
    if cmd.exit_code:
AttributeError: 'str' object has no attribute 'exit_code'

**Comment by Patiiik** [comment]
It's caused by breaking change in sh library. You just need to download older version to get script working.

python3 -m pip install --upgrade "sh==1.12.14" "requests>=2"
